id: P004220
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG18483
  title: ཐར་མདོ།
  author: ''
  volumes:
    3651035497404a6b9be0622e3cb24c18:
      image_group_id: I1KG18485
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
